### ISSUE TITLE
Note and Warning blockquotes improperly rendered

### ISSUE THREAD

**Issue by tanrbobanr** [mjbvz/vscode-github-markdown-preview#25] opened 2023-06-02 17:48 UTC
Currently, the below do not render with the symbol (or text color) while using the extension:

> **Note**
> `**Note**`

> **Warning**
> `**Warning**`

**Comment by mjbvz** [comment] 2023-06-02 21:03
Duplicate of #23

**Closed as completed by mjbvz** 2023-06-02 21:03 UTC
