### ISSUE TITLE
Add Note/Warning

### ISSUE THREAD

**Issue by coolhome** [mjbvz/vscode-github-markdown-preview#22] opened 2023-04-24 23:39 UTC
```
> **Note**
> This is a note

> **Warning**
> This is a warning
```
Produces:
> **Note**
> This is a note

> **Warning**
> This is a warning

**Comment by mjbvz** [comment] 2023-04-24 23:46
Duplicate of https://github.com/mjbvz/vscode-github-markdown-preview/issues/23

**Closed as completed by mjbvz** 2023-04-24 23:46 UTC
